[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.16"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
